### PR TITLE
Gvda nf test - WIP

### PR DESCRIPTION
**Pull request by christopher-hakkaart**

### CODE REVIEW

**Comment by vdauwera** [comment]
Ahh you fixed my linting issues, thank you @christopher-hakkaart !

Was the system really just being pissy about trailing whitespaces, for the most part? 😅

**Comment by christopher-hakkaart** [comment]
> Was the system really just being pissy about trailing whitespaces, for the most part? 😅

Yup - it isn't forgiving

**Comment by ewels** [comment]
@vdauwera - install this and it'll sort out that trailing whitespace every time you hit save: https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode

Linting tool is Prettier: https://prettier.io/ , we use it all over the place.

**Comment by vdauwera** [comment]
@christopher-hakkaart I filled out all the TODOs in the explanations (I think) but haven't added Prettier yet so it's still yelling at me.

**Comment by christopher-hakkaart** [comment]
I'm heading to the airport soon and will have some time to fix it up then. If you're happy with the content I'll tidy the rest.

**Comment by vdauwera** [comment]
I think I might have actually fixed it! Going to run through everything one last time in the latest gitpod; fingers crossed nothing new comes up.

**Comment by christopher-hakkaart** [comment]
Ahhhh great!

**Comment by vdauwera** [comment]
Success! Everything works in my hands. 

I realized I forgot to cover the question of how to run the tests in bulk/automatically (as opposed to running them individually as shown here). I assume the 'right way' is to use github/CI which presumably the nf-core template facilitates; if so that seems like a great tie-in for you since you'll have covered that. Not sure what to put in for this specific training so I'm going to punt and plan to figure that out in the next iteration (ie for Boston).

**Comment by vdauwera** [comment]
Also have a safe flight/smooth trip!

**Comment by mribeirodantas** [comment]
Have a safe flight, @christopher-hakkaart !

Great work, @vdauwera ! 🥳

**Comment by christopher-hakkaart** [comment]
LMGT

**Pull request merged**
