### PR TITLE
Modules redo 23 june

### PR DESCRIPTION
**Pull request by chriswyatt1**

### CODE REVIEW

**Comment by ewels** [comment]
Sorry guys, should have spotted this before doing the markdown conversion. I'll leave it open and will come back to it.

Should be possible to port the changes over by converting the updated asciidoc files to markdown again, then doing a diff of the auto-generated markdown against the new site.

It'll be messy but hopefully not too bad with a little human curation.

**Comment by ewels** [comment]
Reminder for self: conversion is basically https://tinyapps.org/blog/201701240700_convert_asciidoc_to_markdown.html but with `gfm` instead of `markdown_strict`:

```bash
asciidoc -b docbook foo.adoc

iconv -t utf-8 foo.xml | pandoc -f docbook -t gfm --wrap=none | iconv -f utf-8 > foo.md
```

**Comment by mribeirodantas** [comment]
It's few changes so it may be easier to just do the changes manually on the mkdocs version. I can work on that.

**Comment by ewels** [comment]
Ok I just had a go at doing the conversion and figuring out the diff and everything - once I started it became quickly apparent that all of the changes in this pull request have already been applied 😆 

Sure enough, looks like it was all merged as part of https://github.com/nextflow-io/training/pull/95, so I think that this PR can just be closed 👍🏻

**Pull request closed without merging**
