### PR TITLE
Fix file extensions in genotyping example to match expected file types.

### PR DESCRIPTION
**Pull request by robsyme**
In the day 2, we construct a mock workflow. Originally the GenotypeOnInterval and MergeGenotyped processes produced mock "bam" files, which doesn't match the expected file types on a real genotyping process. 

This change replaces the filenames produced in these processes from bam to vcf, which makes following the logic of the pipeline a little easier to track.

### CODE REVIEW

**Comment by vdauwera** [comment]
@robsyme Do you have any plans to update / recycle this or should we just close it?

**Comment by kenibrewer** [comment]
@robsyme Closing this now. Feel free to re-open if you'd like to incorporate changes at a later date.

**Comment by robsyme** [comment]
@kenibrewer and @vdauwera - apologies for missing this. Yes, I'd like to merge in these small changes to the "advanced" module.

**Comment by kenibrewer** [comment]
@robsyme Changes look fine to me. Could you make the PR title and description more informative about the actual changes and then I will approve.

**Comment by robsyme** [comment]
Done. Excellent suggesiton, thanks Ken.

**Review by kenibrewer — APPROVED** [review]

**Pull request merged**
