### PR TITLE
Add nf-core intermediate training

### PR DESCRIPTION
**Pull request by FriederikeHanssen**
**WIP** (still very raw, no use in detailed reviews just yet, just for the overall structure):
 
  This PR adds nf-core intermediate training. 
  
- Create a new pipeline using a reduced template
- Add a nf-core module
- Create a custom module and add it
 
Naming and placing can still be discussed.

### CODE REVIEW

**Comment by kenibrewer** [comment]
@vdauwera I had imagined that this content would go into our existing nf-core module rather than having a separate intermediate training. Is that what you had in mind too?

**Comment by vdauwera** [comment]
Yes, however I think we need a planning session to think through the scope and content of the current training modules before we continue adding anything major. Let's schedule that asap so we can figure this out from a whole-course perspective.

**Comment by FriederikeHanssen** [comment]
>  I had imagined that this content would go into our existing nf-core module rather than having a separate intermediate training. Is that what you had in mind too?

I don't really mind where to put this. I just needed a place for the moment. I wasn't sure if you wanted to expand the existing nf-core training or not. and what of this will be moved over to nf-core eventually.

**Comment by FriederikeHanssen** [comment]
Moved it over to #448. broke something with git submodules

**Pull request closed without merging**
